In [85]:
import pandas as pd
# Importing libraries

from __future__ import print_function
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import classification_report
from sklearn import metrics
from sklearn import tree
import warnings
warnings.filterwarnings('ignore')

In [86]:
data = pd.read_excel(r'C:\Users\GOPINATH CHENNAMSETT\Desktop\flaskdemo\crop_csv_file.xlsx')

In [87]:
data.head()

State_Name District_Name  Crop_Year       Season  \
0  Andaman and Nicobar Islands      NICOBARS       2000  Kharif        
1  Andaman and Nicobar Islands      NICOBARS       2000  Kharif        
2  Andaman and Nicobar Islands      NICOBARS       2000  Kharif        
3  Andaman and Nicobar Islands      NICOBARS       2000  Whole Year    
4  Andaman and Nicobar Islands      NICOBARS       2000  Whole Year    

                  Crop  Temperature  humidity  soil moisture    area  \
0             Arecanut           36        35             45  1254.0   
1  Other Kharif pulses           37        40             46     2.0   
2                 Rice           36        41             50   102.0   
3               Banana           37        42             55   176.0   
4            Cashewnut           36        40             54   720.0   

   Production  
0      2000.0  
1         1.0  
2       321.0  
3       641.0  
4       165.0

In [88]:
data.head()
data = data[:10000]

In [89]:
data.head()

State_Name District_Name  Crop_Year       Season  \
0  Andaman and Nicobar Islands      NICOBARS       2000  Kharif        
1  Andaman and Nicobar Islands      NICOBARS       2000  Kharif        
2  Andaman and Nicobar Islands      NICOBARS       2000  Kharif        
3  Andaman and Nicobar Islands      NICOBARS       2000  Whole Year    
4  Andaman and Nicobar Islands      NICOBARS       2000  Whole Year    

                  Crop  Temperature  humidity  soil moisture    area  \
0             Arecanut           36        35             45  1254.0   
1  Other Kharif pulses           37        40             46     2.0   
2                 Rice           36        41             50   102.0   
3               Banana           37        42             55   176.0   
4            Cashewnut           36        40             54   720.0   

   Production  
0      2000.0  
1         1.0  
2       321.0  
3       641.0  
4       165.0

In [90]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   State_Name     10000 non-null  object 
 1   District_Name  10000 non-null  object 
 2   Crop_Year      10000 non-null  int64  
 3   Season         10000 non-null  object 
 4   Crop           10000 non-null  object 
 5   Temperature    10000 non-null  int64  
 6   humidity       10000 non-null  int64  
 7   soil moisture  10000 non-null  int64  
 8    area          10000 non-null  float64
 9   Production     9931 non-null   float64
dtypes: float64(2), int64(4), object(4)
memory usage: 781.4+ KB


In [91]:
data['State_Name'].unique()

array(['Andaman and Nicobar Islands', 'Andhra Pradesh',
       'Arunachal Pradesh'], dtype=object)

In [92]:
data['District_Name'].unique()

array(['NICOBARS', 'NORTH AND MIDDLE ANDAMAN', 'SOUTH ANDAMANS',
       'ANANTAPUR', 'CHITTOOR', 'EAST GODAVARI', 'GUNTUR', 'KADAPA',
       'KRISHNA', 'KURNOOL', 'PRAKASAM', 'SPSR NELLORE', 'SRIKAKULAM',
       'VISAKHAPATANAM', 'VIZIANAGARAM', 'WEST GODAVARI', 'ANJAW',
       'CHANGLANG'], dtype=object)

In [93]:
data['Crop_Year'].unique()

array([2000, 2001, 2002, 2003, 2004, 2005, 2006, 2010, 1997, 1998, 1999,
       2007, 2008, 2009, 2011, 2012, 2013, 2014], dtype=int64)

In [94]:
data['Season'].unique()

array(['Kharif     ', 'Whole Year ', 'Autumn     ', 'Rabi       '],
      dtype=object)

In [95]:
data['Crop'].unique()

array(['Arecanut', 'Other Kharif pulses', 'Rice', 'Banana', 'Cashewnut',
       'Coconut ', 'Dry ginger', 'Sugarcane', 'Sweet potato', 'Tapioca',
       'Black pepper', 'Dry chillies', 'other oilseeds', 'Turmeric',
       'Maize', 'Moong(Green Gram)', 'Urad', 'Arhar/Tur', 'Groundnut',
       'Sunflower', 'Bajra', 'Castor seed', 'Cotton(lint)', 'Horse-gram',
       'Jowar', 'Korra', 'Ragi', 'Tobacco', 'Gram', 'Wheat', 'Masoor',
       'Sesamum', 'Linseed', 'Safflower', 'Onion', 'other misc. pulses',
       'Samai', 'Small millets', 'Coriander', 'Potato',
       'Other  Rabi pulses', 'Soyabean', 'Beans & Mutter(Vegetable)',
       'Bhindi', 'Brinjal', 'Citrus Fruit', 'Cucumber', 'Grapes', 'Mango',
       'Orange', 'other fibres', 'Other Fresh Fruits', 'Other Vegetables',
       'Papaya', 'Pome Fruit', 'Tomato', 'Rapeseed &Mustard', 'Mesta',
       'Cowpea(Lobia)', 'Lemon', 'Pome Granet', 'Sapota', 'Cabbage',
       'Peas  (vegetable)', 'Niger seed', 'Bottle Gourd', 'Sannhamp',
       'Va

In [96]:
#handling missing data
data = data.dropna()
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9931 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   State_Name     9931 non-null   object 
 1   District_Name  9931 non-null   object 
 2   Crop_Year      9931 non-null   int64  
 3   Season         9931 non-null   object 
 4   Crop           9931 non-null   object 
 5   Temperature    9931 non-null   int64  
 6   humidity       9931 non-null   int64  
 7   soil moisture  9931 non-null   int64  
 8    area          9931 non-null   float64
 9   Production     9931 non-null   float64
dtypes: float64(2), int64(4), object(4)
memory usage: 853.4+ KB


In [97]:
data.describe()

Crop_Year  Temperature     humidity  soil moisture           area  \
count  9931.000000  9931.000000  9931.000000    9931.000000    9931.000000   
mean   2006.076025    34.445675    44.773034      53.108146   13299.452361   
std       5.153237     3.499294     6.662943       5.259584   46476.817881   
min    1997.000000    25.000000    35.000000      45.000000       0.200000   
25%    2002.000000    34.000000    40.000000      50.000000     160.000000   
50%    2006.000000    36.000000    42.000000      54.000000    1071.000000   
75%    2011.000000    36.000000    50.000000      55.000000    6265.500000   
max    2014.000000    37.000000    55.000000      62.000000  877029.000000   

         Production  
count  9.931000e+03  
mean   1.816847e+06  
std    2.748270e+07  
min    0.000000e+00  
25%    2.045000e+02  
50%    1.776000e+03  
75%    1.321650e+04  
max    7.801620e+08

In [98]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

State_Name = le.fit_transform(data.State_Name)
District_Name = le.fit_transform(data.District_Name)
Crop_Year = le.fit_transform(data.Crop_Year)
crop = le.fit_transform(data.Crop)
Season = le.fit_transform(data.Season)
data['State_Name'] = State_Name
data['District_Name'] = District_Name
data['Crop_Year'] = Crop_Year
data['Crop'] = crop
data['Season']  = Season

In [124]:
from sklearn.model_selection import train_test_split
#from sklearn.cross_validation import train_test_split
X = data.iloc[:,:-1]
y = data.iloc[:,-1]
X_train,X_test,Y_train,Y_test = train_test_split(X,y,test_size=0.2,random_state=100)

In [126]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import roc_auc_score , classification_report, mean_squared_error, r2_score
forest = RandomForestRegressor(n_estimators=1000, 
                               criterion='mse', 
                               random_state=1, 
                               n_jobs=-1)
forest.fit(X_train, Y_train)
y_train_pred = forest.predict(X_train)
y_test_pred = forest.predict(X_test)

print('MSE train: %.3f, test: %.3f' % (
        mean_squared_error(Y_train, y_train_pred),
        mean_squared_error(Y_test, y_test_pred)))
print('R^2 train: %.3f, test: %.3f' % (
        r2_score(Y_train, y_train_pred),
        r2_score(Y_test, y_test_pred)))

MSE train: 7023640414606.193, test: 43311638797231.828
R^2 train: 0.990, test: 0.958


In [127]:
print(forest.score(X_test,Y_test))

0.9581139626404562


In [128]:
forest.predict(X_test)

array([6.39245193e+05, 2.97393199e+05, 8.57097100e+03, ...,
       8.04864000e+01, 1.12687002e+05, 7.71037200e+03])

In [129]:
X_test

State_Name  District_Name  Crop_Year  Season  Crop  Temperature  \
6880           1             13         15       1    58           36   
9780           1             17         16       2    30           34   
6584           1             13          6       3    40           34   
2073           1              4          7       1     2           37   
123            0             10         13       2    60           34   
...          ...            ...        ...     ...   ...          ...   
3903           1              6         15       2    39           34   
7686           1             14         17       2    24           36   
5839           1             11          7       1    35           35   
2068           1              4          6       3    61           35   
2746           1              5          5       3    40           37   

      humidity  soil moisture     area  
6880        40             54   9896.0  
9780        55             62  50712.0  
6584        45             52   1660.0  
2073        42             55   1840.0  
123         55             62    109.0  
...        ...            ...      ...  
3903        55             62     28.0  
7686        35             45   4852.0  
5839        50             59    126.0  
2068        50             59  18768.0  
2746        40             46   1359.0  

[1987 rows x 9 columns]

# PREDICTION

In [130]:
forest.predict([[1,5,5,3,40,37,40,46,1359.0]])


array([7710.372])

In [131]:
state = input('enter state:')
district = input('enter district:')
year = input('enter year:')
season = input('enter season:')
crop = input('enter crop:')
Temperature = input('enter Temperature')
humidity= input('enter humidity')
soilmoisture= input('enter soilmoisture')
area = input('enter area')

out_1 = forest.predict([[float(state),
       float(district),
       float(year),
       float(season),
       float(crop),
       float(Temperature),
       float(humidity),
       float(soilmoisture),
       float(area)]])
print(out_1)
print('crop yield Production:',out_1)


enter state:1
enter district:1
enter year:1
enter season:1
enter crop:1
enter Temperature23
enter humidity23
enter soilmoisture12
enter area134
[146.379]
crop yield Production: [146.379]


# SAVING MODEL 

In [132]:
import pickle

RF_pkl_filename = r'C:/Users/GOPINATH CHENNAMSETT/Desktop/flaskdemo/RFYield.pkl'
# Open the file to save as pkl file
RF_Model_pkl = open(RF_pkl_filename, 'wb')
pickle.dump(forest, RF_Model_pkl)
# Close the pickle instances
RF_Model_pkl.close()